// API to register user.

POST http://localhost:3000/register
Content-Type: application/json

{
    "username":"ksd",
    "name":"siva dinesh",
    "age" : 23,
    "password":"siva@dinesh"
}
###

//API to Login authorized user..
POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"ksd",
    "password":"siva@dinesh"
}